name: magma-microservices

services:
#  user-service:
#    build:
#      dockerfile: user-service.Dockerfile
#      context: ./
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    environment:
#      NODE_ENV: production
#      DATABASE_URL: "mongodb+srv://konradchw:6EVsAj688EnZ474c@cluster0.iy0oj.mongodb.net/magmamath?retryWrites=true&w=majority&appName=Cluster0"
#      RABBITMQ_URL: "amqp://localhost:5672"
#      NOTIFICATION_QUEUE_NAME: "notification_send"
#    ports:
#      - "3333:3333"

#  notification-service:
#    build:
#      context: ./packages/notification-service
#    depends_on:
#      rabbitmq:
#        condition: service_healthy
#    environment:
#      NODE_ENV: production

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - magma-network

networks:
  magma-network:
    driver: bridge

volumes:
  rabbitmq_data:
