name: magma-microservices

services:
  # mongodb
  #  mongo1:
  #    image: mongo:8.0
  #    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
  #    ports:
  #      - 27017:27017
  #    extra_hosts:
  #      - "host.docker.internal:host-gateway"
  #    healthcheck:
  #      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
  #      interval: 5s
  #      timeout: 30s
  #      start_period: 0s
  #      retries: 30
  #    volumes:
  #      - "mongo1_data:/data/db"
  #      - "mongo1_config:/data/configdb"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - magma-network

networks:
  magma-network:
    driver: bridge

volumes:
  #  mongo1_data:
  #  mongo1_config:
  rabbitmq_data: